export default {
  infor: {
    "allwidth":"300","allheight":"34",
    "isShowStyle3Icon": "open",
    "search4_bc": "#fff",
    "search_div_height_bc": "#fff",
    "search_x_show": "none",
    "search_x_fs": 12,
    "search_x_color": "#000",
    "search_x_top": 0,
    "search_x_right": 0,
    "search_input_placeholder_color": "#000",
    "search_placeholder_fs": 14,
    "icon_class": "icon iconfont icon-search4",
    "search_oppen_style": "0",
    "search_text_border_radius": 0,
    "search_btn_icon_margin_top": 0,
    "search_btn_icon_margin_right": 0,
    "search_btn_icon_margin_bottom": 0,
    "search_btn_icon_margin_left": 0,
    "search_btn_icon_padding_top": 0,
    "search_btn_icon_padding_right": 0,
    "search_btn_icon_padding_bottom": 0,
    "search_btn_icon_padding_left": 0,
    "search_btn_icon_div_width": 40,
    "search_btn_icon_div_height": 40,
    "search_is_show_icon": "block",
    "search_is_show_txt": "block",
    "search_btn_icon_fs": 24,
    "search_btn_icon_color": "#f0f",
    "search_text_fs": 12,
    "search_text_text_align": "center",
    "search_text_pos_left": 260,
    "search_text_pos_right": 0,
    "search_width": 300,
    "search_height": 34,
    "search_div_width": 400,
    "search_div_height": 40,
    "search_input_fs": 18,
    "search_padding_left": 34,
    "search_padding_right": 4,
    "search_placeholder": "请输入查询信息",
    "search_absolute_left": 0,
    "search_absolute_top": 0,
    "search_radius": 6,
    "search_text_width": 40,
    "search_text_height": 34,
    "search_text_color": "#f00",
    "search_text_font_color": "#000",
    "search_icon_color": "#f0f",
    "search_input_color": "#000",
    "is_show_icon": true,
    "show_icon": "",
    "show_text": "",
    "search_icon_width": 24,
    "search_btn_text": "搜索",
    "open_style": true,
    "search_margin_left": 0,
    "search_margin_top": 0,
    "styleId": "w1111",
    "searchs_border_top_style": "solid",
    "searchs_border_top_color": "#ccc",
    "searchs_border_top_width": 1,
    "searchs_border_right_style": "solid",
    "searchs_border_right_width": 1,
    "searchs_border_bottom_style": "solid",
    "searchs_border_bottom_width": 1,
    "searchs_border_left_style": "solid",
    "searchs_border_left_width": 1,
    "searchs_border_right_color": "#ccc",
    "searchs_border_bottom_color": "#ccc",
    "searchs_border_left_color": "#ccc",
    "search_input_bg_color": "#fff",
    "widget_loading": "基础",
    "widget_loading_li": "无动画",
    "widget_animateds": "",
    "widget_scroll_loading_checked": false,
    "widget_scroll_loading": false,
    "widget_scroll_loading_location_checked": false,
    "widget_scroll_loading_location": false,
    "widget_scroll_loading_location_height": 0,
    "pic_iteration_checked2": false,
    "pic_iteration2": "no",
    "animation_countsss": 1,
    "animation_durasss": 1,
    "animation_delaysss": 0,
    "search5_select_width": 20,
    "search5_select_height": 20,
    "search5_select_fs": 12,
    "search5_icon_width": 20,
    "search5_icon_height": 20
},
  listArr: {
  },
  animateObj: {
    animatedType: '',
    animatedDuration: 0.5,
    animatedDelay: 0,
    animatedIterationCount: false,
    animatedState: ''
  },
  DefaultStyle:[
      {
          id:'w1111',
          name:'系统默认样式1',
          style:'{"allwidth":"300","allheight":"34","isShowStyle3Icon":"open","search4_bc":"#fff","search_div_height_bc":"#fff","search_x_show":"none","search_x_fs":12,"search_x_color":"#000","search_x_top":0,"search_x_right":0,"search_input_placeholder_color":"#000","search_placeholder_fs":14,"icon_class":"icon iconfont icon-search4","search_oppen_style":"0","search_text_border_radius":0,"search_btn_icon_margin_top":0,"search_btn_icon_margin_right":0,"search_btn_icon_margin_bottom":0,"search_btn_icon_margin_left":0,"search_btn_icon_padding_top":0,"search_btn_icon_padding_right":0,"search_btn_icon_padding_bottom":0,"search_btn_icon_padding_left":0,"search_btn_icon_div_width":40,"search_btn_icon_div_height":40,"search_is_show_icon":"block","search_is_show_txt":"none","search_btn_icon_fs":24,"search_btn_icon_color":"#f0f","search_text_fs":12,"search_text_text_align":"center","search_text_pos_left":0,"search_text_pos_right":0,"search_width":300,"search_height":34,"search_div_width":400,"search_div_height":40,"search_input_fs":18,"search_padding_left":34,"search_padding_right":4,"search_placeholder":"请输入查询信息","search_absolute_left":0,"search_absolute_top":0,"search_radius":6,"search_text_width":40,"search_text_height":34,"search_text_color":"#f00","search_text_font_color":"#000","search_icon_color":"#f0f","search_input_color":"#000","is_show_icon":true,"show_icon":"","show_text":"","search_icon_width":24,"search_btn_text":"搜索","open_style":true,"search_margin_left":0,"search_margin_top":0,"styleId":"w1111","searchs_border_top_style":"solid","searchs_border_top_color":"#ccc","searchs_border_top_width":1,"searchs_border_right_style":"solid","searchs_border_right_width":1,"searchs_border_bottom_style":"solid","searchs_border_bottom_width":1,"searchs_border_left_style":"solid","searchs_border_left_width":1,"searchs_border_right_color":"#ccc","searchs_border_bottom_color":"#ccc","searchs_border_left_color":"#ccc","search_input_bg_color":"#fff","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"search5_select_width":20,"search5_select_height":20,"search5_select_fs":12,"search5_icon_width":20,"search5_icon_height":20}',
          img:'/static/image/graphicInfo/search1.png'
      },
      {
          id:'w2222',
          name:'系统默认样式2',
          style:'{"allwidth":"305","allheight":"92","isShowStyle3Icon":"open","search4_bc":"#fff","search_div_height_bc":"#fff","search_x_show":"none","search_x_fs":12,"search_x_color":"#000","search_x_top":0,"search_x_right":0,"search_input_placeholder_color":"#000","search_placeholder_fs":14,"icon_class":"icon iconfont icon-search14","search_oppen_style":"1","search_text_border_radius":0,"search_btn_icon_margin_top":0,"search_btn_icon_margin_right":0,"search_btn_icon_margin_bottom":12,"search_btn_icon_margin_left":0,"search_btn_icon_padding_top":0,"search_btn_icon_padding_right":0,"search_btn_icon_padding_bottom":0,"search_btn_icon_padding_left":120,"search_btn_icon_div_width":40,"search_btn_icon_div_height":40,"search_is_show_icon":"block","search_is_show_txt":"none","search_btn_icon_fs":24,"search_btn_icon_color":"#000","search_text_fs":12,"search_text_text_align":"center","search_text_pos_left":0,"search_text_pos_right":0,"search_width":300,"search_height":34,"search_div_width":400,"search_div_height":40,"search_input_fs":18,"search_padding_left":34,"search_padding_right":4,"search_placeholder":"请输入查询信息","search_absolute_left":0,"search_absolute_top":0,"search_radius":6,"search_text_width":40,"search_text_height":34,"search_text_color":"#f00","search_text_font_color":"#000","search_icon_color":"#0ff","search_input_color":"#000","is_show_icon":true,"show_icon":"","show_text":"","search_icon_width":24,"search_btn_text":"搜索","open_style":true,"search_margin_left":0,"search_margin_top":0,"styleId":"w2222","searchs_border_top_style":"solid","searchs_border_top_color":"#ccc","searchs_border_top_width":1,"searchs_border_right_style":"solid","searchs_border_right_color":"#ccc","searchs_border_right_width":1,"searchs_border_bottom_style":"solid","searchs_border_bottom_color":"#ccc","searchs_border_bottom_width":1,"searchs_border_left_style":"solid","searchs_border_left_color":"#ccc","searchs_border_left_width":1,"search_input_bg_color":"#fff","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"search5_select_width":20,"search5_select_height":20,"search5_select_fs":12,"search5_icon_width":20,"search5_icon_height":20}',
          img:'/static/image/graphicInfo/search2.png'
      },
      /* {
          id:'w3333',
          name:'系统默认样式3',
          style:'{"allwidth":"308","allheight":"92","isShowStyle3Icon":"open","search4_bc":"#fff","search_div_height_bc":"#fff","search_x_show":"none","search_x_fs":12,"search_x_color":"#000","search_x_top":0,"search_x_right":0,"search_input_placeholder_color":"#000","search_placeholder_fs":14,"icon_class":"icon iconfont icon-search3","search_oppen_style":"2","search_text_border_radius":0,"search_btn_icon_margin_top":0,"search_btn_icon_margin_right":0,"search_btn_icon_margin_bottom":12,"search_btn_icon_margin_left":0,"search_btn_icon_padding_top":0,"search_btn_icon_padding_right":0,"search_btn_icon_padding_bottom":0,"search_btn_icon_padding_left":140,"search_btn_icon_div_width":40,"search_btn_icon_div_height":40,"search_is_show_icon":"block","search_is_show_txt":"none","search_btn_icon_fs":24,"search_btn_icon_color":"#0f0","search_text_fs":12,"search_text_text_align":"center","search_text_pos_left":0,"search_text_pos_right":0,"search_width":300,"search_height":34,"search_div_width":240,"search_div_height":180,"search_input_fs":18,"search_padding_left":34,"search_padding_right":4,"search_placeholder":"请输入查询信息","search_absolute_left":0,"search_absolute_top":0,"search_radius":6,"search_text_width":40,"search_text_height":34,"search_text_color":"#f00","search_text_font_color":"#000","search_icon_color":"#0ff","search_input_color":"#000","is_show_icon":true,"show_icon":"","show_text":"","search_icon_width":24,"search_btn_text":"搜索","open_style":true,"search_margin_left":0,"search_margin_top":0,"styleId":"w3333","searchs_border_top_style":"solid","searchs_border_top_width":1,"searchs_border_right_style":"solid","searchs_border_right_width":1,"searchs_border_bottom_style":"solid","searchs_border_bottom_width":1,"searchs_border_left_style":"solid","searchs_border_left_width":1,"searchs_border_top_color":"#ccc","searchs_border_right_color":"#ccc","searchs_border_bottom_color":"#ccc","searchs_border_left_color":"#ccc","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"search5_select_width":20,"search5_select_height":20,"search5_select_fs":12,"search5_icon_width":20,"search5_icon_height":20}',
          img:'/static/image/graphicInfo/search3.png'
      }, */
      {
          id:'w4444',
          name:'系统默认样式3',
          style:'{"allwidth":"340","allheight":"64","isShowStyle3Icon":"open","search_div_height_bc":"#fff","search_x_show":"none","search_x_fs":12,"search_x_color":"#000","search_x_top":0,"search_x_right":0,"search_input_placeholder_color":"#000","search_placeholder_fs":14,"icon_class":"icon iconfont icon-search4","search_oppen_style":"3","search_text_border_radius":0,"search_btn_icon_margin_top":0,"search_btn_icon_margin_right":0,"search_btn_icon_margin_bottom":12,"search_btn_icon_margin_left":296,"search_btn_icon_padding_top":0,"search_btn_icon_padding_right":0,"search_btn_icon_padding_bottom":0,"search_btn_icon_padding_left":140,"search_btn_icon_div_width":40,"search_btn_icon_div_height":60,"search_is_show_icon":"block","search_is_show_txt":"none","search_btn_icon_fs":14,"search_btn_icon_color":"#ffff00","search_text_fs":12,"search_text_text_align":"center","search_text_pos_left":0,"search_text_pos_right":0,"search_width":300,"search_height":34,"search_div_width":240,"search_div_height":180,"search_input_fs":18,"search_padding_left":12,"search_padding_right":4,"search_placeholder":"请输入查询信息","search_absolute_left":0,"search_absolute_top":0,"search_radius":6,"search_text_width":40,"search_text_height":34,"search_text_color":"#f00","search_text_font_color":"#000","search_icon_color":"#0ff","search_input_color":"#000","is_show_icon":true,"show_icon":"","show_text":"","search_icon_width":24,"search_btn_text":"搜索","open_style":true,"search_margin_left":0,"search_margin_top":14,"styleId":"w4444","searchs_border_top_style":"solid","searchs_border_top_width":1,"searchs_border_right_style":"solid","searchs_border_right_width":1,"searchs_border_bottom_style":"solid","searchs_border_bottom_width":1,"searchs_border_left_style":"solid","searchs_border_left_width":1,"searchs_border_top_color":"#ccc","searchs_border_right_color":"#ccc","searchs_border_bottom_color":"#ccc","searchs_border_left_color":"#ccc","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"search4_bc":"#d9d9d9","search_input_bg_color":"#ffffff","search5_select_width":20,"search5_select_height":20,"search5_select_fs":12,"search5_icon_width":20,"search5_icon_height":20}',
          img:'/static/image/graphicInfo/search4.png'
      },
      {
          id:'w555',
          name:'系统默认样式4',
          style:'{"allwidth":"466","allheight":"40","isShowStyle3Icon":"open","search_div_height_bc":"#fff","search_x_show":"none","search_x_fs":12,"search_x_color":"#000","search_x_top":0,"search_x_right":0,"search_input_placeholder_color":"#000","search_placeholder_fs":14,"icon_class":"icon iconfont icon-search4","search_oppen_style":"4","search_text_border_radius":0,"search_btn_icon_margin_top":0,"search_btn_icon_margin_right":0,"search_btn_icon_margin_bottom":12,"search_btn_icon_margin_left":296,"search_btn_icon_padding_top":0,"search_btn_icon_padding_right":0,"search_btn_icon_padding_bottom":0,"search_btn_icon_padding_left":140,"search_btn_icon_div_width":40,"search_btn_icon_div_height":60,"search_is_show_icon":"block","search_is_show_txt":"none","search_btn_icon_fs":14,"search_btn_icon_color":"#ffff00","search_text_fs":12,"search_text_text_align":"center","search_text_pos_left":0,"search_text_pos_right":0,"search_width":300,"search_height":34,"search_div_width":240,"search_div_height":180,"search_input_fs":18,"search_padding_left":12,"search_padding_right":0,"search_placeholder":"请输入查询信息","search_absolute_left":0,"search_absolute_top":0,"search_radius":0,"search_text_width":40,"search_text_height":34,"search_text_color":"#f00","search_text_font_color":"#000","search_icon_color":"#000","search_input_color":"#000","is_show_icon":true,"show_icon":"","show_text":"","search_icon_width":20,"search_btn_text":"搜索","open_style":true,"search_margin_left":0,"search_margin_top":0,"styleId":"w555","searchs_border_top_style":"solid","searchs_border_top_width":1,"searchs_border_right_style":"solid","searchs_border_right_width":1,"searchs_border_bottom_style":"solid","searchs_border_bottom_width":1,"searchs_border_left_style":"solid","searchs_border_left_width":1,"searchs_border_top_color":"#ccc","searchs_border_right_color":"#ccc","searchs_border_bottom_color":"#ccc","searchs_border_left_color":"#ccc","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"search4_bc":"#d9d9d9","search_input_bg_color":"#ffffff","search5_select_width":100,"search5_select_height":34,"search5_select_fs":13,"search5_icon_width":60,"search5_icon_height":34,"search5_select_color":"#434343","search5_select_bc":"#eee","search5_icon_bc":"#eee"}',
          img:'/static/image/graphicInfo/search5.png'
      }
  ]
};
