// export { default as formText } from './text.vue'
export { default as formText } from './text'
export { default as formTextarea } from './textarea'
export { default as formSelect } from './select'
export { default as formMultipleselect } from './multipleselect'
export { default as formRadios } from './radios'
export { default as formButton } from './button'
export { default as formDoublebutton } from './doublebutton'
export { default as formYzm } from './yzm'
