export default {
    infor:{
      "allwidth":"800","allheight":"200",
      datas:['招聘职位','招聘单位','招聘期限','招聘人数','薪资待遇'],
      job_detail_height:24,
      job_detail_title_width:70,
      job_detail_title_fs:16,
      job_detail_title_fs_color:"#000",
      job_detail_con_fs:14,
      job_detail_con_fs_color:"#333",
      job3_con_value1:"subject",
      job_detail_is_show_title:"block",
      job_detail_a_bc_color:"#e5e5e5",
      job_detail_a_fs_color:"#fff",
      job_detail_a_bc_color_hover:"#fff",
      job_detail_a_fs_color_hover:"#f0f",
      job_detail_a_width:80,
      job_detail_a_height:50,
      job_detail_a_fs:16,
      job_detail_a_border_radius:18,
      job_detail_a_margin_top:0,
      job_detail_a_margin_left:0,
      job_detail_a_con:"投递简历"
    },listArr:{
        
    },
    animateObj:{
      animatedType:'',
      animatedDuration:0.5,
      animatedDelay:0,
      animatedIterationCount:false,
      animatedState:'',
    },
    DefaultStyle:[
      {
          id:'w1111',
          name:'系统默认样式1',
          style:'{"allwidth":"800","allheight":"200","job_detail_height":24,"job_detail_title_width":70,"job_detail_title_fs":16,"job_detail_title_fs_color":"#000","job_detail_con_fs":14,"job_detail_con_fs_color":"#333","job3_con_value1":"subject","job_detail_is_show_title":"block","job_detail_a_bc_color":"#000","job_detail_a_fs_color":"#fff","job_detail_a_bc_color_hover":"#fff","job_detail_a_fs_color_hover":"#f0f","job_detail_a_width":80,"job_detail_a_height":50,"job_detail_a_fs":16,"job_detail_a_border_radius":18,"job_detail_a_margin_top":0,"job_detail_a_margin_left":0,"job_detail_a_con":"投递简历"}',
          img:'/static/image/graphicInfo/jobdetail1.png'
      }
  ]
}