export default {
  infor:{
    bannerSet:{
      btn:'block',
      pagination:'block',
      time:1000,
      speed:300,
      animation:'slide',
      pattern:'horizontal',
      width:500,
      height:300,
      slideWidth:300,
      slideOpacity:0.7,
      slideModifier:2
    },
    textEffect:{
      color:'#666',
      fontSize:20,
      in:'flash',
      out:'bounce',
      display:'none',
      left:0,
      top:0
    },
    btnStyle:{
      leftIcon:'fa-angle-double-left',
      rightIcon:'fa-angle-double-right',
      background:'#5874d8',
      fontSize:30,
      color:'#ccc',
      width:50,
      height:80,
      marginTop:1,
      marginLR:1,
      borderRadius:0
    },
    pageStyle:{
      background:'#fff',
      selectbackground:'#f00',
      width:20,
      height:20,
      margin:5,
      borderColor:'#333',
      textAlign:'center',
      type:'point',
      left:100,
      bottom:10,
      borderWidth:5,
      borderRadius:0
    },

    effectsObj:{
      type:'',//特效类型
      icon:'fa-adjust',//icon图标
      iconSize:50,//icon大小
      iconColor:'#fff',//icon颜色
      changeSrc:'/static/image/pic.png',//替换图片
      borderStyle:'solid',//边框类型
      borderWidth:1,//边框尺寸
      borderColor:'#ccc',//边框颜色
      deg:90,//旋转角度
      zoom:1.5,//放大的倍率
      distance:20,//位移距离
    }
  },
  listArr: {
    picList: []
  },
  animateObj:{
    animatedType:'',
    animatedDuration:0.5,
    animatedDelay:0,
    animatedIterationCount:false,
    animatedState:'',
  },
    DefaultStyle:[
        {
            id:'s001',
            name:'分页器居左',
            style:'{"bannerSet":{"btn":"block","pagination":"block","time":1000,"speed":300,"animation":"fade","pattern":"horizontal","width":500,"height":300},"textEffect":{"color":"#666","fontSize":20,"in":"flash","out":"bounce","display":"none","left":0,"top":0},"btnStyle":{"borderRadius":0,"marginTop":0,"marginLR":0,"leftIcon":"fa-caret-square-o-left","rightIcon":"fa-toggle-right","background":"#f00","fontSize":40,"color":"#fff","width":50,"height":80},"pageStyle":{"background":"#fff","selectbackground":"#f00","width":20,"height":20,"margin":5,"borderColor":"#333","textAlign":"center","type":"point","left":100,"bottom":10,"borderWidth":5,"borderRadius":0},"effectsObj":{"type":"","icon":"fa-adjust","iconSize":50,"iconColor":"#fff","changeSrc":"","borderStyle":"solid","borderWidth":1,"borderColor":"#ccc","deg":90,"zoom":1.5,"distance":20}}',
            img:'/static/image/DefaultStyle/banner1.jpg'
        },

        {
            id:'s002',
            name:'分页器居中',
            style:'{"bannerSet":{"btn":"block","pagination":"block","time":1000,"speed":300,"animation":"fade","pattern":"horizontal","width":500,"height":300},"textEffect":{"color":"#666","fontSize":20,"in":"flash","out":"bounce","display":"none","left":0,"top":0},"btnStyle":{"borderRadius":0,"marginTop":0,"marginLR":0,"leftIcon":"fa-angle-left","rightIcon":"fa-angle-right","background":"#f00","fontSize":40,"color":"#fff","width":50,"height":80},"pageStyle":{"background":"#fff","selectbackground":"#f00","width":20,"height":20,"margin":5,"borderColor":"#333","textAlign":"center","type":"point","left":100,"bottom":10,"borderWidth":5,"borderRadius":0},"effectsObj":{"type":"","icon":"fa-adjust","iconSize":50,"iconColor":"#fff","changeSrc":"","borderStyle":"solid","borderWidth":1,"borderColor":"#ccc","deg":90,"zoom":1.5,"distance":20}}',
            img:'/static/image/DefaultStyle/banner2.jpg'
        },
    ],

};
