export default {
    infor: {
        loop:'false',
        pattern: 'horizontal', //模式选择
        patternWidth:1000,
        patternHeight: 310, //模式容器的高度,
        patternPadding:0, //模式容器的补白,
        patternBorderType: 'none', //模式容器的边框类型,
        patternBordercolor: '#ccc', //模式容器的边框颜色,
        patternBorderSize: 0, //模式容器的边框粗细,
        patternAutoplay: 5000, //自动滚动时间间隔
        patternSpace: 10, //模块间隔
        patternSlidesPerView: 3, //单页显示个数
        patternSlidesRow:1,
        patternDisplay:'block',
        classOpen: false, //分类是否开启
        btnStyle:{
            leftIcon:'fa-angle-double-left',
            rightIcon:'fa-angle-double-right',
            background:'#f00',
            fontSize:16,
            color:'#fff',
            width:50,
            height:80,
            display:'block',
            top:0,
            left:10
        },
        classStyle:{
            selectPattern:'hover',
            background:'#ccc',
            selectbackground:'#f2f2f2',
            width:80,
            height:30,
            margin:5,
            borderColor:'#333',
            fontSize:16,
            color:'#ff0',
            selectcolor:'#fff',
            boxWidth:300,
            boxHeight:40,
            boxMarginLeft:0,
            selectborderColor:'#f00'
        },
        Mongolia:{
            width:323,
            height:306,
            marginLeft:0,
            marginTop:0,
            background:'#ccc',
            opacity:0.3,
            animation:'fade',
            time:200,
            direction:'up',
            isOpen:'false',
        },
        MongoliaIcon:{
            display:'block',
            color:'#fff',
            fontSize:24,
            icon:'fa-adjust'
        },
        MongoliaTitle:{
            display:'block',
            color:'#fff',
            fontSize:24,
            fontFamily:'Microsoft YaHei',
            lineHeight:30,
            width:300,
            height:30,
        },
        MongoliaContent:{
            display:'block',
            color:'#f00',
            fontSize:24,
            fontFamily:'Microsoft YaHei',
            lineHeight:30,
            width:300,
            height:30,
        },
        pic: {
            width: 305,
            height:170,
            margin: 10,
            display:'block',
            marginTop:5,
            marginLeft:5,
            marginRight:5,
            marginBottom:5
        },
        title: {
            color: '#565656',
            fontSize: 14,
            textAlign: 'left',
            width:100,
            height: 40,
            marginTop:5,
            marginBottom:5,
            marginLeft:5,
            marginRight:5,
            display:'block',
            paddingLeft:2,
            paddingTop:2,
            paddingBottom:2,
            paddingRight:2,
            borderLeftWidth:1,
            borderRightWidth:1,
            borderTopWidth:1,
            borderBottomWidth:1,
            borderColor:'#ccc',
            borderStyle:'solid',
            borderRadius:5,
            fontWeight:'normal',
            Scolor: '#f2f2f2',
            SfontSize: 16,
        },
        //序列
        sequence: {
            color: '#565656',
            fontSize: 14,
            textAlign:'center',
            width: 40,
            height: 40,
            marginTop:5,
            marginBottom:5,
            marginLeft:5,
            marginRight:5,
            display:'block',
            borderLeftWidth:1,
            borderRightWidth:1,
            borderTopWidth:1,
            borderBottomWidth:1,
            borderColor:'#ccc',
            borderStyle:'solid',
            fontWeight:'normal',
            Scolor: '#f00',
            SfontSize: 16,
        },
        content: {
            color: '#565656',
            fontSize: 14,
            textAlign: 'left',
            width: 305,
            height:40,
            marginTop:5,
            marginBottom:5,
            marginLeft:5,
            marginRight:5,
            lineHeight:20,
            display:'block',
            Scolor: '#f00',
            SfontSize: 16,
            textLength:20
        },
        model: {
            background: '#fff',
            borderStyle: 'solid',
            borderTopColor: "#565656",
            borderBottomColor: "#565656",
            borderLeftColor: "#565656",
            borderRightColor: "#565656",
            borderSize: 1,
            target:'_blank',
            height:310,
        },
        header: {
            name: '我是标题',
            display:'none',
            height: 50,
            color: '#565656',
            textAlign: 'left',
            fontSize: 18,
            fontWeight:'normal',
        },
        classTitle: {
            color: '#565656',
            fontSize: 14,
            textAlign: 'left',
            width: 40,
            height: 40,
            marginTop: 5,
            marginBottom:5,
            marginLeft:5,
            marginRight:5,
            display:'block',
            paddingLeft:2,
            paddingTop:2,
            paddingBottom:2,
            paddingRight:2,
            borderLeftWidth:1,
            borderRightWidth:1,
            borderTopWidth:1,
            borderBottomWidth:1,
            borderColor:'#ccc',
            borderStyle:'solid',
            borderRadius:5,
            fontWeight:'normal',
            background:'#ccc'
        },
        time:{
            color: '#565656',
            fontSize: 14,
            textAlign: 'left',
            width:66,
            height:25,
            marginTop:5,
            marginBottom:5,
            marginLeft:5,
            marginRight:5,
            display:'block',
            timePattern:'ordinary',
            day_line_height:40,
            day_fontsize:18,
            year_line_height:20,
            year_fontsize:12,
            background:'#ccc',
            Scolor: '#f00',
            SfontSize: 16,
        },

    },
    listArr:{
        listArr: [],//列表数组
        classArr: [],
        Mongolia:{
            icon:'icon-chakan'
        },
        listType:'productNew',
        RelevantLimit:3
    },
      animateObj:{
        animatedType:'',
        animatedDuration:0.5,
        animatedDelay:0,
        animatedIterationCount:false,
        animatedState:'',
      },
    DefaultStyle:[
        {
            id:'s001',
            name:'横向模式',
            style:'{"loop":"false","pattern":"horizontal","patternWidth":1000,"patternHeight":310,"patternPadding":0,"patternBorderType":"none","patternBordercolor":"#ccc","patternBorderSize":0,"patternAutoplay":1000,"patternSpace":10,"patternSlidesPerView":3,"patternSlidesRow":1,"patternDisplay":"block","classOpen":true,"btnStyle":{"leftIcon":"fa-angle-double-left","rightIcon":"fa-angle-double-right","background":"#f00","fontSize":16,"color":"#ccc","width":50,"height":80,"display":"block","top":0,"left":10},"classStyle":{"selectPattern":"hover","background":"#ccc","selectbackground":"#f2f2f2","width":80,"height":30,"margin":5,"borderColor":"#333","fontSize":16,"color":"#ff0","selectcolor":"#fff","boxWidth":300,"boxHeight":40,"boxMarginLeft":0},"Mongolia":{"width":400,"height":400,"marginLeft":0,"marginTop":0,"background":"#ccc","opacity":0.3,"animation":"fade","time":200,"direction":"up","isOpen":"false"},"MongoliaIcon":{"display":"block","color":"#fff","fontSize":24,"icon":"fa-adjust"},"MongoliaTitle":{"display":"block","color":"#fff","fontSize":24,"fontFamily":"Microsoft YaHei","lineHeight":30,"width":300,"height":30},"MongoliaContent":{"display":"block","color":"#f00","fontSize":24,"fontFamily":"Microsoft YaHei","lineHeight":30,"width":300,"height":30},"pic":{"width":305,"height":170,"margin":10,"display":"block","marginTop":5,"marginLeft":5,"marginRight":5,"marginBottom":5},"title":{"color":"#565656","fontSize":14,"textAlign":"left","width":100,"height":40,"marginTop":5,"marginBottom":5,"marginLeft":5,"marginRight":5,"display":"block","paddingLeft":2,"paddingTop":2,"paddingBottom":2,"paddingRight":2,"borderLeftWidth":1,"borderRightWidth":1,"borderTopWidth":1,"borderBottomWidth":1,"borderColor":"#ccc","borderStyle":"solid","borderRadius":5,"fontWeight":"normal","Scolor":"#f2f2f2","SfontSize":16},"sequence":{"color":"#565656","fontSize":14,"textAlign":"left","width":40,"height":40,"marginTop":5,"marginBottom":5,"marginLeft":5,"marginRight":5,"display":"block","borderLeftWidth":1,"borderRightWidth":1,"borderTopWidth":1,"borderBottomWidth":1,"borderColor":"#ccc","borderStyle":"solid","fontWeight":"normal","Scolor":"#f00","SfontSize":16},"content":{"color":"#565656","fontSize":14,"textAlign":"left","width":305,"height":40,"marginTop":5,"marginBottom":5,"marginLeft":5,"marginRight":5,"lineHeight":20,"display":"block","Scolor":"#f00","SfontSize":16,"textLength":20},"model":{"background":"#fff","borderStyle":"solid","borderTopColor":"#565656","borderBottomColor":"#565656","borderLeftColor":"#565656","borderRightColor":"#565656","borderSize":1,"target":"_blank","height":320},"header":{"name":"","display":"none","height":50,"color":"#565656","textAlign":"left","fontSize":18,"fontWeight":"normal"},"classTitle":{"color":"#565656","fontSize":14,"textAlign":"left","width":40,"height":40,"marginTop":5,"marginBottom":5,"marginLeft":5,"marginRight":5,"display":"block","paddingLeft":2,"paddingTop":2,"paddingBottom":2,"paddingRight":2,"borderLeftWidth":1,"borderRightWidth":1,"borderTopWidth":1,"borderBottomWidth":1,"borderColor":"#ccc","borderStyle":"solid","borderRadius":5,"fontWeight":"normal","background":"#ccc"},"time":{"color":"#565656","fontSize":14,"textAlign":"left","width":66,"height":25,"marginTop":5,"marginBottom":5,"marginLeft":5,"marginRight":5,"display":"block","timePattern":"ordinary","day_line_height":40,"day_fontsize":18,"year_line_height":20,"year_fontsize":12,"background":"#ccc","Scolor":"#f00","SfontSize":16},"effectsObj":{"type":"","icon":"fa-adjust","iconSize":50,"iconColor":"#fff","changeSrc":"","borderStyle":"solid","borderWidth":1,"borderColor":"#ccc","deg":90,"zoom":1.5,"distance":20}}',
            img:'/static/image/DefaultStyle/classList1.jpg'
        }
    ]

};


