export default [
    {
        styleId:'nav1',
        src:'../../../static/image/nav1-nei.jpg',
        title:'主题名称：红黑车轮纹理导航'
    },
    {
        styleId:'nav2',
        src:'../../../static/image/nav2-nei.jpg',
        title:'主题名称：简约黑底红字导航'
    },
    {
        styleId:'nav3',
        src:'../../../static/image/nav3-nei.jpg',
        title:'主题名称：橙色经典通屏导航'
    },
    {
        styleId:'nav4',
        src:'../../../static/image/nav4-nei.jpg',
        title:'主题名称：橙色经典通屏导航'
    },
    {
        styleId:'nav5',
        src:'../../../static/image/nav5-nei.png',
        title:'主题名称：灰色典雅导航'
    },
    {
        styleId:'nav6',
        src:'../../../static/image/nav6-nei.jpg',
        title:'主题名称：清新雅绿通用导航'
    },
    {
        styleId:'nav7',
        src:'../../../static/image/nav7-nei.jpg',
        title:'主题名称：橙橘渐变简约导航'
    },
    {
        styleId:'nav8',
        src:'../../../static/image/nav8-nei.jpg',
        title:'主题名称：紫色高端时尚导航'
    },
    {
        styleId:'nav9',
        src:'../../../static/image/nav9-nei.png',
        title:'主题名称：黑色质感通栏导航'
    },
    {
        styleId:'nav10',
        src:'../../../static/image/nav10-nei.jpg',
        title:'主题名称：蓝色质感导航'
    },
    {
        styleId:'nav11',
        src:'../../../static/image/nav11-nei.jpg',
        title:'主题名称：蓝色渐变导航'
    },
]