export default {
  infor:{
    frameBox:200,
    frameHeight:330,
    modeSelection:'vertical',
    animation:'toggle',
    animationTime:600,
    sort:'float',
    numShow:6,
    padding:5,
    btn:{
      width:40,
      fontSzie:14,
      background:'#666',
      color:'#fff',
      borderColor:'#f00',
      borderRadius:3
    },
    box:{
      width:200,
      height:300,
      borderColor:'#ccc',
      borderStyle:'dashed',
      borderWidth:1,
      background:'#f00',
      padding:1
    },
    title:{
      content:'我是分类列表',
      height:30,
      fontSize:12,
      fontFamily:'Microsoft YaHei',
      background:'#e3e3e3',
      color:'#f00',
      fontWeight:'bolder',
      fontAlign:'center',
      display:'block',
      paddingLeft:10
    },
    onelevel:{
      fontWeight:'bolder',
      fontAlign:'center',
      fontSize:12,
      fontFamily:'Microsoft YaHei',
      background:'#f56608',
      color:'#fff',
      width:200,
      height:40,
      borderColor:'#ccc',
      borderStyle:'solid',
      borderRadius:5,
      seleFontSize:12,
      seleBackground:'#ccc',
      seleColor:'#000',
      borderTopWidth:0,
      borderBottomWidth:0,
      borderleftWidth:0,
      borderRightWidth:0,
      paddingLeft:20,
    },
    twolevel:{
      fontWeight:'bolder',
      fontAlign:'center',
      fontSize:12,
      fontFamily:'Microsoft YaHei',
      background:'#ccc',
      color:'#fff',
      width:180,
      height:30,
      borderColor:'#ccc',
      borderStyle:'solid',
      borderRadius:3,
      seleFontSize:14,
      seleBackground:'#f00',
      seleColor:'#fff',
      boxWidth:1000,
      boxHeight:40,
      margin:10,
      borderTopWidth:0,
      borderBottomWidth:0,
      borderleftWidth:0,
      borderRightWidth:0,
      paddingLeft:10,
    },
    threelevel:{
      fontWeight:'bolder',
      fontAlign:'center',
      fontSize:12,
      fontFamily:'Microsoft YaHei',
      background:'#069805',
      color:'#333',
      width:160,
      height:30,
      borderColor:'#ccc',
      borderStyle:'solid',
      borderRadius:3,
      seleFontSize:12,
      seleBackground:'#054c98',
      seleColor:'#fff900',
      borderTopWidth:0,
      borderBottomWidth:0,
      borderleftWidth:0,
      borderRightWidth:0,
      paddingLeft:5,
    },
    //styleId:''
  },
  listArr:{
    title:{
      content:'我是分类列表'
    }
  },
  animateObj:{
    animatedType:'',
    animatedDuration:0.5,
    animatedDelay:0,
    animatedIterationCount:false,
    animatedState:'',
  },
  DefaultStyle:[
    {
      id:'s001',
      name:'竖向样式',
      style:'{"frameBox":200,"frameHeight":330,"btn":{"width":40,"fontSzie":14,"background":"#666","color":"#fff","borderColor":"#f00","borderRadius":3},"modeSelection":"vertical","animation":"toggle","animationTime":600,"sort":"float","numShow":6,"padding":5,"box":{"height":300,"width":200,"borderColor":"#ccc","borderStyle":"dashed","borderWidth":1,"background":"#fff","padding":1},"title":{"paddingLeft":10,"content":"我是分类列表","height":30,"fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f00","color":"#FFFFFF","fontWeight":"normal","fontAlign":"center","display":"block"},"onelevel":{"paddingLeft":20,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f56608","color":"#fff","width":200,"height":40,"borderColor":"#ccc","borderStyle":"solid","borderRadius":5,"seleFontSize":12,"seleBackground":"#ccc","seleColor":"#000"},"twolevel":{"paddingLeft":10,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#ccc","color":"#fff","width":180,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":14,"seleBackground":"#f00","seleColor":"#fff"},"threelevel":{"paddingLeft":5,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#069805","color":"#333","width":160,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":12,"seleBackground":"#054c98","seleColor":"#fff900"}}',
      img:'/static/image/DefaultStyle/class1.jpg'
    },

    {
      id:'s002',
      name:'横向超出滚动',
      style:'{"frameBox":605,"frameHeight":200,"btn":{"width":40,"fontSzie":14,"background":"#666","color":"#fff","borderColor":"#f00","borderRadius":3},"modeSelection":"horizontal","animation":"toggle","animationTime":600,"sort":"swiper","numShow":6,"padding":5,"box":{"width":500,"borderColor":"#ccc","borderStyle":"solid","borderWidth":1,"background":"#FFFFFF","padding":1},"title":{"paddingLeft":10,"content":"我是分类列表","height":30,"fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f00","color":"#FFFFFF","fontWeight":"normal","fontAlign":"center","display":"block"},"onelevel":{"paddingLeft":20,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f56608","color":"#fff","width":200,"height":40,"borderColor":"#ccc","borderStyle":"solid","borderRadius":5,"seleFontSize":12,"seleBackground":"#ccc","seleColor":"#000"},"twolevel":{"paddingLeft":5,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#ccc","color":"#fff","width":110,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":14,"seleBackground":"#f00","seleColor":"#fff"},"threelevel":{"paddingLeft":5,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#069805","color":"#333","width":110,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":12,"seleBackground":"#054c98","seleColor":"#fff900"}}',
      img:'/static/image/DefaultStyle/class2.jpg'
    },
    {
      id:'s003',
      name:'横向超出换行',
      style:'{"frameBox":605,"frameHeight":300,"btn":{"width":40,"fontSzie":14,"background":"#666","color":"#fff","borderColor":"#f00","borderRadius":3},"modeSelection":"horizontal","animation":"toggle","animationTime":600,"sort":"float","numShow":6,"padding":5,"box":{"width":500,"borderColor":"#ccc","borderStyle":"solid","borderWidth":1,"background":"#FFFFFF","padding":1},"title":{"paddingLeft":10,"content":"我是分类列表","height":30,"fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f00","color":"#FFFFFF","fontWeight":"normal","fontAlign":"center","display":"block"},"onelevel":{"paddingLeft":20,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#f56608","color":"#fff","width":110,"height":40,"borderColor":"#ccc","borderStyle":"solid","borderRadius":5,"seleFontSize":12,"seleBackground":"#ccc","seleColor":"#000"},"twolevel":{"paddingLeft":10,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"boxHeight":40,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#ccc","color":"#fff","width":110,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":14,"seleBackground":"#f00","seleColor":"#fff"},"threelevel":{"paddingLeft":5,"borderTopWidth":0,"borderBottomWidth":0,"borderleftWidth":0,"borderRightWidth":0,"fontWeight":"normal","fontAlign":"left","fontSize":12,"fontFamily":"MicrosoftYaHei","background":"#069805","color":"#333","width":110,"height":30,"borderColor":"#ccc","borderStyle":"solid","borderRadius":3,"seleFontSize":12,"seleBackground":"#054c98","seleColor":"#fff900"}}',
      img:'/static/image/DefaultStyle/class3.jpg'
    }
  ],

};
