export default {
  infor: {
    allwidth: 80,
    allheight: 40,
    width: 400,
    height: 44,
    isShows: false,
    newwidth: 100,
    w_link_decoration_link: 'none',
    w_link_decoration_visited: 'none',
    w_link_decoration_hover: 'none',
    w_link_decoration_active: 'none',
    icon_pos_left: 0,
    icon_pos_top: 0,
    w_icon_fillr: 0,
    w_icon_fillleft: 0,
    w_icon_fillbtm: 0,
    w_icon_filltop: 0,
    w_link_fillleft: 0,
    w_link_fillr: 0,
    w_link_fillbtm: 0,
    w_link_filltop: 0,
    w_link_family: 'SimSun',
    w_link_bold: 'normal',
    w_link_fs: 12,
    w_link_dir: 'left',
    w_color_fs: 12,
    w_icon_color: '#f00',
    w_link_bg_color: '#fff',
    w_link_bg_hover_color: '#ff0',
    w_link_color: '#333',
    w_link_hover_color: '#0f0',
    clickName: 0,
    cityList: [
      {
        linkTitles: 'link_title1',
        linkLinks: 'link_href1',
        linkTargets: 'link_target1',
        linkAddPic: '添加图',
        linkDelPic: '删除图',
        imgalt: 'imgalt1',
        imgUrl: '',
        isShowPic: 'false',
        isShowPics: 'isShowPics1',
        imgUrls: 'imgUrls1',
        linkDeletes: '删除行'
      }
    ],
    cityLists: [
      {
        title: '',
        href: '',
        target: '_self',
        iconCLass: '',
        imgalt: '',
        isShowPic: 'false',
        isShowPics: 'false',
        imgUrls: '',
        backgroundImage:'',
        backgroundImageHover:''
      }
    ],
    rowNumber: 1,
    isShowWarn: false,
    widget: '',
    links_styles: '0',
    w_color_width: 80,
    w_color_height: 40,
    w_link_text_align: "center",
    w_flinks_width: 180,
    w_flinks_height: 50,
    w_flink_text_align: "center",
    w_flinks_bc_color: "#ccc",
    w_flinks_font_color: "#0f0",
    w_flinks_con: "友情链接",
    w_links_emit_styles: "click",
    w_flinks_font_size: 18,
    w_links_sport_time: 1000,
    w_links_sport_styles: "slide",
    w_flinks_icon_left: 20,
    w_flinks_icon_top: 20,
    w_flinks_border_radius: 0,
    imgUrls: [],
    switchArr: ['false'],
    w_flinks_pic_width: 200,
    w_flinks_pic_height: 100,
    w_flinks_pic_left: 50,
    w_flinks_pic_top: 20,
    w_link_bold_first: 'normal',
    w_link_text_align_first: "center",
    w_link_color_first: '#fff',
    w_link_hover_color_first: '#ff0',
    w_link_bg_color_first: '#e5e5e5',
    w_link_bg_hover_color_first: '#0f0',
    w_color_width_first: 80,
    w_color_height_first: 40,
    w_link_fs_first: 18,
    w_link_open_first_set: '1',
    w_link_margin_left: 0,
    w_link_margin_right: 0,
    w_link_margin_top: 0,
    w_link_margin_bottom: 0,
    w_link_border_top_border_style: 'solid',
    w_link_border_top_border_color: "#000",
    w_link_border_top_border_width: 0,
    w_link_border_right_border_style: 'solid',
    w_link_border_right_border_color: "#000",
    w_link_border_right_border_width: 0,
    w_link_border_bottom_border_style: 'solid',
    w_link_border_bottom_border_color: "#000",
    w_link_border_bottom_border_width: 0,
    w_link_border_left_border_style: 'solid',
    w_link_border_left_border_color: "#000",
    w_link_border_left_border_width: 0,
    w_link_hover_border_top_border_style: 'solid',
    w_link_hover_border_top_border_color: "#000",
    w_link_hover_border_top_border_width: 0,
    w_link_hover_border_right_border_style: 'solid',
    w_link_hover_border_right_border_color: "#000",
    w_link_hover_border_right_border_width: 0,
    w_link_hover_border_bottom_border_style: 'solid',
    w_link_hover_border_bottom_border_color: "#000",
    w_link_hover_border_bottom_border_width: 0,
    w_link_hover_border_left_border_style: 'solid',
    w_link_hover_border_left_border_color: "#000",
    w_link_hover_border_left_border_width: 0,
    w_color_lineheight: 40,
    w_link_first_mt: 0,
    w_link_first_mb: 0,
    w_link_first_ml: 0,
    w_link_first_mr: 0,
    w_link_first_pt: 0,
    w_link_first_pb: 0,
    w_link_first_pl: 0,
    w_link_first_pr: 0,
    w_link_first_br: 0,
    w_link_second_br: 0,
    w_firlink_border_top_border_style: 'solid',
    w_firlink_border_top_border_color: "#000",
    w_firlink_border_top_border_width: 0,
    w_firlink_border_right_border_style: 'solid',
    w_firlink_border_right_border_color: "#000",
    w_firlink_border_right_border_width: 0,
    w_firlink_border_bottom_border_style: 'solid',
    w_firlink_border_bottom_border_color: "#000",
    w_firlink_border_bottom_border_width: 0,
    w_firlink_border_left_border_style: 'solid',
    w_firlink_border_left_border_color: "#000",
    w_firlink_border_left_border_width: 0,
    w_firlink_hover_border_top_border_style: 'solid',
    w_firlink_hover_border_top_border_color: "#000",
    w_firlink_hover_border_top_border_width: 0,
    w_firlink_hover_border_right_border_style: 'solid',
    w_firlink_hover_border_right_border_color: "#000",
    w_firlink_hover_border_right_border_width: 0,
    w_firlink_hover_border_bottom_border_style: 'solid',
    w_firlink_hover_border_bottom_border_color: "#000",
    w_firlink_hover_border_bottom_border_width: 0,
    w_firlink_hover_border_left_border_style: 'solid',
    w_firlink_hover_border_left_border_color: "#000",
    w_firlink_hover_border_left_border_width: 0,
  }, listArr: {

  },
  animateObj: {
    animatedType: '',
    animatedDuration: 0.5,
    animatedDelay: 0,
    animatedIterationCount: false,
    animatedState: '',
  },
  DefaultStyle: [
    {
      id: 'w1111',
      name: '系统默认样式1',
      style: '{"w_link_first_br": 0,"w_link_second_br": 0,"allwidth":"240","allheight":"40","w_link_first_mt":0,"w_link_first_mb":0,"w_link_first_ml":0,"w_link_first_mr":0,"w_link_first_pt":0,"w_link_first_pb":0,"w_link_first_pl":0,"w_link_first_pr":0,"w_link_bold_first":"normal","w_link_text_align_first":"center","w_link_color_first":"#fff","w_link_hover_color_first":"#ff0","w_link_bg_color_first":"#333","w_link_bg_hover_color_first":"#0f0","w_color_width_first":80,"w_color_height_first":40,"w_link_fs_first":18,"w_link_decoration_link":"none","w_link_decoration_visited":"none","w_link_decoration_hover":"none","w_link_decoration_active":"none","icon_pos_left":0,"icon_pos_top":0,"w_icon_fillr":0,"w_icon_fillleft":10,"w_icon_fillbtm":0,"w_icon_filltop":0,"w_link_fillleft":0,"w_link_fillr":0,"w_link_fillbtm":0,"w_link_filltop":0,"w_link_family":"SimSun","w_link_bold":"normal","w_link_fs":12,"w_link_dir":"left","w_color_fs":16,"w_icon_color":"#f00","w_link_bg_color":"rgba(255, 255, 255, 1)","w_link_bg_hover_color":"rgba(255, 255, 0, 1)","w_link_color":"rgba(51, 51, 51, 1)","w_link_hover_color":"rgba(0, 255, 0, 1)","clickName":2,"cityList":[{"linkTitles":"link_title1","linkLinks":"link_href1","linkTargets":"link_target1","linkAddPic":"添加图","linkDelPic":"删除图","imgalt":"imgalt1","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics1","imgUrls":"imgUrls1","linkDeletes":"删除行"},{"linkTitles":"link_title2","linkLinks":"link_href2","linkTargets":"link_target2","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics2","imgUrls":"imgUrls2","imgalt":"imgalt2","linkDeletes":"删除行"},{"linkTitles":"link_title3","linkLinks":"link_href3","linkTargets":"link_target3","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics3","imgUrls":"imgUrls3","imgalt":"imgalt3","linkDeletes":"删除行"}],"cityLists":[{"title":"首页","href":"","target":"_blank","iconCLass":"fa-home","imgalt":"","isShowPic":"false","isShowPics":"false","imgUrls":""},{"title":"链接","href":"","target":"_self","iconCLass":"fa-link","imgalt":"","isShowPic":"false","isShowPics":"false","imgUrls":""},{"title":"联系","href":"","target":"_blank","iconCLass":"fa-group","imgalt":"","isShowPic":"false","isShowPics":"false","imgUrls":""}],"rowNumber":3,"isShowWarn":false,"widget":"","links_styles":"0","w_color_width":80,"w_color_height":40,"w_color_lineheight":40,"w_link_text_align":"center","w_flinks_width":180,"w_flinks_height":50,"w_flink_text_align":"center","w_flinks_bc_color":"#ccc","w_flinks_font_color":"#0f0","w_flinks_con":"友情链接","w_links_emit_styles":"click","w_flinks_font_size":18,"w_links_sport_time":1000,"w_links_sport_styles":"slide","w_flinks_icon_left":20,"w_flinks_icon_top":20,"w_flinks_border_radius":0,"imgUrls":[],"switchArr":["false"],"w_flinks_pic_width":200,"w_flinks_pic_height":100,"w_flinks_pic_left":50,"w_flinks_pic_top":20,"link_title1":"首页","link_title2":"链接","link_title3":"联系","link_target1":"_self","link_target2":"_blank","link_target3":"_self","styleId":"w1111","w_link_open_first_set":"0","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"w_link_margin_left":0,"w_link_margin_right":0,"w_link_margin_top":0,"w_link_margin_bottom":0,"w_link_border_top_border_style":"solid","w_link_border_top_border_color":"#000","w_link_border_top_border_width":0,"w_link_border_right_border_style":"solid","w_link_border_right_border_color":"#000","w_link_border_right_border_width":0,"w_link_border_bottom_border_style":"solid","w_link_border_bottom_border_color":"#000","w_link_border_bottom_border_width":0,"w_link_border_left_border_style":"solid","w_link_border_left_border_color":"#000","w_link_border_left_border_width":0,"w_link_hover_border_top_border_style":"solid","w_link_hover_border_top_border_color":"#000","w_link_hover_border_top_border_width":0,"w_link_hover_border_right_border_style":"solid","w_link_hover_border_right_border_color":"#000","w_link_hover_border_right_border_width":0,"w_link_hover_border_bottom_border_style":"solid","w_link_hover_border_bottom_border_color":"#000","w_link_hover_border_bottom_border_width":0,"w_link_hover_border_left_border_style":"solid","w_link_hover_border_left_border_color":"#000","w_link_hover_border_left_border_width":0,"isShows":false,"effectsObj":{"type":"","icon":"fa-adjust","iconSize":50,"iconColor":"#fff","changeSrc":"","borderStyle":"solid","borderWidth":1,"borderColor":"#ccc","deg":90,"zoom":1.5,"distance":20}}',
      img: '/static/image/graphicInfo/links1.png'
    },
    {
      id: 'w2222',
      name: '系统默认样式2',
      style: '{"w_link_first_br": 0,"w_link_second_br": 0,"allwidth":182,"allheight":177,"w_link_first_mt":0,"w_link_first_mb":0,"w_link_first_ml":0,"w_link_first_mr":0,"w_link_first_pt":0,"w_link_first_pb":0,"w_link_first_pl":0,"w_link_first_pr":0,"w_link_bold_first":"normal","w_link_text_align_first":"center","w_link_color_first":"#fff","w_link_hover_color_first":"#ff0","w_link_bg_color_first":"#333","w_link_bg_hover_color_first":"#0f0","w_color_width_first":80,"w_color_height_first":40,"w_link_fs_first":18,"w_link_decoration_link":"none","w_link_decoration_visited":"none","w_link_decoration_hover":"none","w_link_decoration_active":"none","icon_pos_left":0,"icon_pos_top":0,"w_icon_fillr":0,"w_icon_fillleft":5,"w_icon_fillbtm":0,"w_icon_filltop":0,"w_link_fillleft":0,"w_link_fillr":0,"w_link_fillbtm":0,"w_link_filltop":0,"w_link_family":"SimSun","w_link_bold":"normal","w_link_fs":12,"w_link_dir":"none","w_color_fs":12,"w_icon_color":"#f00","w_link_bg_color":"#fff","w_link_bg_hover_color":"#ff0","w_link_color":"#333","w_link_hover_color":"#0f0","clickName":2,"cityList":[{"linkTitles":"link_title1","linkLinks":"link_href1","linkTargets":"link_target1","linkAddPic":"添加图","linkDelPic":"删除图","imgalt":"imgalt1","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics1","imgUrls":"imgUrls1","linkDeletes":"删除行"},{"linkTitles":"link_title2","linkLinks":"link_href2","linkTargets":"link_target2","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics2","imgUrls":"imgUrls2","imgalt":"imgalt2","linkDeletes":"删除行"},{"linkTitles":"link_title3","linkLinks":"link_href3","linkTargets":"link_target3","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics3","imgUrls":"imgUrls3","imgalt":"imgalt3","linkDeletes":"删除行"}],"cityLists":[{"title":"首页","href":"","target":"_self","iconCLass":"fa-home","imgalt":"","isShowPic":"false","isShowPics":"false","imgUrls":""},{"title":"链接","href":"","target":"_self","iconCLass":"fa-link","imgalt":"","isShowPic":"false","isShowPics":"","imgUrls":""},{"title":"关于","href":"","target":"_self","iconCLass":"fa-group","imgalt":"","isShowPic":"false","isShowPics":"","imgUrls":""}],"rowNumber":3,"isShowWarn":false,"widget":"","links_styles":"1","w_color_width":99,"w_color_height":40,"w_color_lineheight":40,"w_link_text_align":"center","w_flinks_width":180,"w_flinks_height":50,"w_flink_text_align":"center","w_flinks_bc_color":"#ccc","w_flinks_font_color":"#0f0","w_flinks_con":"友情链接","w_links_emit_styles":"click","w_flinks_font_size":18,"w_links_sport_time":1000,"w_links_sport_styles":"slide","w_flinks_icon_left":26,"w_flinks_icon_top":16,"w_flinks_border_radius":0,"imgUrls":[],"switchArr":["false"],"w_flinks_pic_width":200,"w_flinks_pic_height":100,"w_flinks_pic_left":50,"w_flinks_pic_top":20,"link_title1":"首页","link_title2":"链接","link_title3":"关于","link_target1":"_blank","link_target2":"_self","link_target3":"_blank","styleId":"w2222","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"w_link_margin_left":0,"w_link_margin_right":0,"w_link_margin_top":0,"w_link_margin_bottom":0,"w_link_border_top_border_style":"solid","w_link_border_top_border_color":"#000","w_link_border_top_border_width":0,"w_link_border_right_border_style":"solid","w_link_border_right_border_color":"#000","w_link_border_right_border_width":0,"w_link_border_bottom_border_style":"solid","w_link_border_bottom_border_color":"#000","w_link_border_bottom_border_width":0,"w_link_border_left_border_style":"solid","w_link_border_left_border_color":"#000","w_link_border_left_border_width":0,"w_link_hover_border_top_border_style":"solid","w_link_hover_border_top_border_color":"#000","w_link_hover_border_top_border_width":0,"w_link_hover_border_right_border_style":"solid","w_link_hover_border_right_border_color":"#000","w_link_hover_border_right_border_width":0,"w_link_hover_border_bottom_border_style":"solid","w_link_hover_border_bottom_border_color":"#000","w_link_hover_border_bottom_border_width":0,"w_link_hover_border_left_border_style":"solid","w_link_hover_border_left_border_color":"#000","w_link_hover_border_left_border_width":0}',
      img: '/static/image/graphicInfo/links2.png'
    },
    {
      id: 'w3333',
      name: '系统默认样式3',
      style: '{"w_link_first_br": 0,"w_link_second_br": 0,"allwidth":182,"allheight":171,"w_link_first_mt":0,"w_link_first_mb":0,"w_link_first_ml":0,"w_link_first_mr":0,"w_link_first_pt":0,"w_link_first_pb":0,"w_link_first_pl":0,"w_link_first_pr":0,"w_link_bold_first":"normal","w_link_text_align_first":"center","w_link_color_first":"#fff","w_link_hover_color_first":"#ff0","w_link_bg_color_first":"#333","w_link_bg_hover_color_first":"#0f0","w_color_width_first":80,"w_color_height_first":40,"w_link_fs_first":18,"w_link_decoration_link":"none","w_link_decoration_visited":"none","w_link_decoration_hover":"none","w_link_decoration_active":"none","icon_pos_left":0,"icon_pos_top":0,"w_icon_fillr":0,"w_icon_fillleft":5,"w_icon_fillbtm":0,"w_icon_filltop":0,"w_link_fillleft":0,"w_link_fillr":0,"w_link_fillbtm":0,"w_link_filltop":0,"w_link_family":"SimSun","w_link_bold":"normal","w_link_fs":12,"w_link_dir":"none","w_color_fs":12,"w_icon_color":"#f00","w_link_bg_color":"#fff","w_link_bg_hover_color":"#ff0","w_link_color":"#333","w_link_hover_color":"#0f0","clickName":2,"cityList":[{"linkTitles":"link_title1","linkLinks":"link_href1","linkTargets":"link_target1","linkAddPic":"添加图","linkDelPic":"删除图","imgalt":"imgalt1","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics1","imgUrls":"imgUrls1","linkDeletes":"删除行"},{"linkTitles":"link_title2","linkLinks":"link_href2","linkTargets":"link_target2","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics2","imgUrls":"imgUrls2","imgalt":"imgalt2","linkDeletes":"删除行"},{"linkTitles":"link_title3","linkLinks":"link_href3","linkTargets":"link_target3","linkAddPic":"添加图","linkDelPic":"删除图","imgUrl":"","isShowPic":"false","isShowPics":"isShowPics3","imgUrls":"imgUrls3","imgalt":"imgalt3","linkDeletes":"删除行"}],"cityLists":[{"title":"首页","href":"","target":"_self","iconCLass":"fa-home","imgalt":"","isShowPic":"false","isShowPics":"false","imgUrls":""},{"title":"链接","href":"","target":"_self","iconCLass":"fa-link","imgalt":"","isShowPic":"false","isShowPics":"","imgUrls":""},{"title":"关于","href":"","target":"_self","iconCLass":"fa-group","imgalt":"","isShowPic":"false","isShowPics":"","imgUrls":""}],"rowNumber":3,"isShowWarn":false,"widget":"","links_styles":"2","w_color_width":99,"w_color_height":40,"w_color_lineheight":40,"w_link_text_align":"center","w_flinks_width":180,"w_flinks_height":50,"w_flink_text_align":"center","w_flinks_bc_color":"#ccc","w_flinks_font_color":"#0f0","w_flinks_con":"友情链接","w_links_emit_styles":"click","w_flinks_font_size":18,"w_links_sport_time":1000,"w_links_sport_styles":"slide","w_flinks_icon_left":26,"w_flinks_icon_top":16,"w_flinks_border_radius":0,"imgUrls":[],"switchArr":["false"],"w_flinks_pic_width":200,"w_flinks_pic_height":100,"w_flinks_pic_left":50,"w_flinks_pic_top":20,"link_title1":"首页","link_title2":"链接","link_title3":"关于","link_target1":"_blank","link_target2":"_self","link_target3":"_blank","styleId":"w3333","w_link_open_first_set":"","widget_loading":"基础","widget_loading_li":"无动画","widget_animateds":"","widget_scroll_loading_checked":false,"widget_scroll_loading":false,"widget_scroll_loading_location_checked":false,"widget_scroll_loading_location":false,"widget_scroll_loading_location_height":0,"pic_iteration_checked2":false,"pic_iteration2":"no","animation_countsss":1,"animation_durasss":1,"animation_delaysss":0,"w_link_margin_left":0,"w_link_margin_right":0,"w_link_margin_top":0,"w_link_margin_bottom":0,"w_link_border_top_border_style":"solid","w_link_border_top_border_color":"#000","w_link_border_top_border_width":0,"w_link_border_right_border_style":"solid","w_link_border_right_border_color":"#000","w_link_border_right_border_width":0,"w_link_border_bottom_border_style":"solid","w_link_border_bottom_border_color":"#000","w_link_border_bottom_border_width":0,"w_link_border_left_border_style":"solid","w_link_border_left_border_color":"#000","w_link_border_left_border_width":0,"w_link_hover_border_top_border_style":"solid","w_link_hover_border_top_border_color":"#000","w_link_hover_border_top_border_width":0,"w_link_hover_border_right_border_style":"solid","w_link_hover_border_right_border_color":"#000","w_link_hover_border_right_border_width":0,"w_link_hover_border_bottom_border_style":"solid","w_link_hover_border_bottom_border_color":"#000","w_link_hover_border_bottom_border_width":0,"w_link_hover_border_left_border_style":"solid","w_link_hover_border_left_border_color":"#000","w_link_hover_border_left_border_width":0}',
      img: '/static/image/graphicInfo/links3.png'
    }
  ]
}